// <auto-generated />
using KrakenMPSPConsole;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace KrakenMPSPConsole.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    [Migration("20190911130511_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("KrakenMPSPCrawler.Models.LegalPersonModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CNPJ");

                    b.Property<string>("CPFDoFundador");

                    b.Property<string>("Contador");

                    b.Property<string>("NomeFantasia");

                    b.HasKey("Id");

                    b.ToTable("LegalPerson");
                });

            modelBuilder.Entity("KrakenMPSPCrawler.Models.PhysicalPersonModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CPF");

                    b.Property<string>("DataDeNascimento");

                    b.Property<string>("NomeCompleto");

                    b.Property<string>("NomeDaMae");

                    b.Property<string>("RG");

                    b.HasKey("Id");

                    b.ToTable("PhysicalPerson");
                });
#pragma warning restore 612, 618
        }
    }
}
